### ISSUE TITLE
Wrong quantities computation

### ISSUE THREAD

**Issue by SnakePy92** [AstronIsTaken/du-craft#7]
Your tool is great but quantities computation is false. For example, for 1 Advanced Antimatter Capsule, the needed petalite qty is 1.93l not 130l without skills.

Details : it needs 2 Ag-Li--> 2 * 50 / 75 = 1.33 Lithium --> 1.33 * 65 / 45 = 1.93l  Petalite

**Comment by AstronIsTaken** [comment]
Hi,
It looks like you calculate 'average' numbers if you craft infinite number of items. Tool uses batching, so it calculates based on what you would really need if you craft just 1 item. Try crafting 1000 Capsules and divide result by 1000 (note: tool might freeze if you enter too big number) - it would be close to number you expect to see.

I'm working on update to show average numbers as well but it will take a while since I'm a bit busy with life right now.

**Comment by SnakePy92** [comment]
Hi, i understood the way you compute it, 2 Ag-Li --> two times lithium production = 2 * 65 L, it make sense too.

There is an easy workaround by asking  for 10000  items to craft.

Thanks again for your tool.
